# Generated by Django 2.2.1 on 2019-05-11 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('Language', models.CharField(max_length=20)),
                ('Farm', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='farm.farm')),
            ],
        ),
    ]
