# Generated by Django 2.2.1 on 2019-05-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.IntegerField()),
                ('Village', models.CharField(max_length=20)),
                ('CropGrown', models.CharField(max_length=20)),
                ('SowingDate', models.DateField()),
            ],
        ),
    ]
