# Generated by Django 2.2.1 on 2019-05-16 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.IntegerField()),
                ('Village', models.CharField(max_length=20)),
                ('CropGrown', models.CharField(max_length=20)),
                ('SowingDate', models.DateField()),
                ('Owner', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Farms', to='farmer.farmer')),
            ],
        ),
    ]
