# Generated by Django 2.2.1 on 2019-05-15 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0001_initial'),
        ('fertilizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DaysAfterSowing', models.PositiveIntegerField()),
                ('Quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Unit', models.CharField(max_length=3)),
                ('Farm', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Schedules', to='farm.farm')),
                ('Fertilizer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='fertilizer.fertilizer')),
            ],
        ),
    ]
